### ISSUE TITLE
Crash when resizing windows

### ISSUE THREAD

**Issue by johanfforsberg** [pdoane/zig-imgui#1]
Hi, this looks great!

However, I tried it and it starts up fine, but then when I start playing around with the window size it crashes quite quickly, with a message like
``` 
info(mach): found Vulkan backend on Discrete GPU adapter: AMD Radeon RX 570 Series (RADV POLARIS10), radv: Mesa 23.1.2
error: gpu: validation error: Viewport bounds (x: 0.000000, y: 0.000000, width: 1658.000122, height: 881.000000) are not contained in the render target dimensions (1658 x 881).
 - While encoding [RenderPassEncoder].SetViewport(0.000000, 0.000000, 1658.000122, 881.000000, 0.000000, 1.000000).
```
I figured there might be a rounding error somewhere, and I think I managed to eliminate the crash by adding in `imgui_mach.zig` line 588:
```
            pass_encoder.setViewport(0, 0, @round(width), @round(height), 0, 1);
```
but this was after a few minutes of investigation and of course might not be the correct way.

This is on Ubuntu 23.04 with AMD GPU, zig 0.12.0-dev.1092+68ed78775

**Comment by pdoane** [comment]
I pushed a fix that uses the framebuffer size directly instead of trying to recompute it.  Let me know if that helps!

**Comment by johanfforsberg** [comment]
Thanks, it appears to solve the issue perfectly. That was quick!
